### ISSUE TITLE
Auto save after deleting layer caused IllegalStateException

### ISSUE THREAD

**Issue by mvsoder** [avereon/carta#106]
IllegalStateException: Duplicate key null (attempted merging values {layers=[1ee775ba-30a4-4146-ab69-87f237748421, da655d30-c00c-4d5c-8d54-5cf296f4e83a, dbaa28cc-d0eb-4e99-88df-517dfd98a243, 98907219-428c-49e9-a612-e30267de7f88]} and {layers=[1ee775ba-30a4-4146-ab69-87f237748421, da655d30-c00c-4d5c-8d54-5cf296f4e83a, be0cfbe1-04db-4d50-a646-510cc04094fc, 4c7d9fe0-fc19-4e93-b43e-699572251cd4, 98907219-428c-49e9-a612-e30267de7f88]})
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.avereon.cartesia/com.avereon.cartesia.CartesiaDesignCodec.mapDesign(CartesiaDesignCodec.java:251)
	at com.avereon.cartesia/com.avereon.cartesia.CartesiaDesignCodec.save(CartesiaDesignCodec.java:118)
	at com.avereon.xenon/com.avereon.xenon.scheme.FileScheme.save(FileScheme.java:72)
	at com.avereon.xenon/com.avereon.xenon.asset.Asset.save(Asset.java:320)
	at com.avereon.xenon/com.avereon.xenon.asset.AssetManager.doSaveAsset(AssetManager.java:1125)
	at com.avereon.xenon/com.avereon.xenon.asset.AssetManager$SaveAssetTask.doOperation(AssetManager.java:1641)
	at com.avereon.xenon/com.avereon.xenon.asset.AssetManager$AssetTask.call(AssetManager.java:1564)
	at com.avereon.xenon/com.avereon.xenon.asset.AssetManager$AssetTask.call(AssetManager.java:1542)
	at com.avereon.xenon/com.avereon.xenon.task.Task$TaskCallable.call(Task.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.avereon.xenon/com.avereon.xenon.task.Task.run(Task.java:90)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at com.avereon.xenon/com.avereon.xenon.task.TaskThread.run(TaskThread.java:16)

**Comment by mvsoder** [comment]
We are unable to duplicate this bug in the current code base
